version: '3'

services:
  payload:
    image: node:18-alpine
    ports:
      - '3040:3040'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - mongo
    environment:
      DATABASE_URI: mongodb://<User>:<Pass>@mongo/DragNDrop?authSource=admin
      PAYLOAD_SECRET: <TuCodigoSecreto>

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    environment:
      MONGO_INITDB_ROOT_USERNAME: <User>
      MONGO_INITDB_ROOT_PASSWORD: <Pass>
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
